# This enables the use of CXS Content Services

backbase.flow.storage:
  impl: cs
  cs:
    repository:
      id: usOnboarding
      name: US Onboarding Storage
      description: US Onboarding store private repository.
