export const interactionConfig = {
  actionConfig: {
    'submit-anchor-data': { updateCdo: true },
    'submit-address': { updateCdo: true },
    'submit-ssn': { updateCdo: true },
    'account-type-selector': { updateCdo: true },
    'request-otp': { updateCdo: true },
    'verify-otp': { updateCdo: true },
    'setup-credentials': { updateCdo: true },
    'submit-kyc-data': { updateCdo: true },
    'agree-to-terms': { updateCdo: true },
    'empty-handler': { updateCdo: false },
    'kyc-questions-loader': { updateCdo: false },
    'identity-verification-initiation': { updateCdo: false },
    'identity-verification-result': { updateCdo: false },
    'fetch-co-applicant-data': { updateCdo: false },
    'select-products': { updateCdo: true },
    'citizenship-selector': { updateCdo: false },
    'fetch-citizenship-data': { updateCdo: false },
    'submit-non-resident-data': { updateCdo: true },
  },
  steps: {
    init: ['init'],
    'anchor-data': ['anchor-data'],
    address: ['address'],
    'co-applicant': ['co-applicant'],
    'co-applicant-data': ['co-applicant-data'],
    'co-applicant-address': ['co-applicant-address'],
    'otp-verification': ['otp-verification'],
    credentials: ['credentials'],
    welcome: ['fetch-co-applicant-data'],
    kyc: ['kyc'],
    'terms-and-conditions': ['terms-and-conditions'],
    'identity-verification': ['identity-verification'],
    'successfully-done': ['successfully-done'],
    'successfully-done-co-applicant': ['successfully-done-co-applicant'],
    'in-review-done': ['in-review-done'],
    retry: ['retry'],
    declined: ['declined'],
    'select-products': ['select-products'],
    citizenship: ['citizenship'],
    ssn: ['ssn'],
    'non-resident-data': ['non-resident-data'],
  },
};
